### ISSUE TITLE
Improvements to Heading component sizing

### ISSUE THREAD

**Issue by rezrah** [primer/brand#101]
### Background
The `Heading` component currently accepts an `as` prop with valid values of `h1`, `h2`, `h3`, `h4`, `h5` and `h6`. 

The same values are then applied to the rendered output. E.g. `as="h2"` will render a `<h2>`.

Default styling is provided for each heading size, based on the the type scale for headings. E.g. `h2` maps to `800` on the type scale.

### The problem space

The tight-coupling of semantic tags to text sizing creates ergonomic challenges consumer side, and is too rigid for app-side use.

Where granular control is often required around heading sizing, the only option available to escape the defaults are to pass a custom CSS class.

E.g. in #100, where example layouts have been provided in Storybook but incorrect `as` sizing is used to meet the visual needs of the examples.

### Proposed solution

Add escape hatches to the Heading API, in the form of a size prop. This would override the default sizing and allow more granular control over the in-browser visuals. 

E.g.

```jsx
<Heading as="h2" size="4">A h2 sized to look like a h4</Heading>
```
This API would avoid a breaking change by maintaining the existing guardrails and system defaults. It would however, offer a sufficient escape-hatch for app developers that continues to align with our type scale.

**Comment by ashygee** [comment]
@rezrah I think the `size` prop feels weird that the values are separate from the values on the scale. If we use scale values could we use `400, 500, 800` etc.? Or even, use the pixel size values that we're going to be applying in Primer Primitives?

**Comment by rezrah** [comment]
@ashygee yes totally. I recall a conversation about the hundred naming convention being confusing, which is why I did it this way? Effectively the only options are 1-6.. which correspond to the default sizing or h1-h6. I can definitely move it over to that scale, but it does feel more abstract to me and requires assumed knowledge of that scale.

**Comment by ashygee** [comment]
@rezrah and I discussed this and I completely understand the single digits now. the number refers to the heading level size to be rendered. Therefore `size="3"` = the size used by default in an H3 (previously rendered in CSS with `.h3-mktg`)
