### ISSUE TITLE
Component API consistency

### ISSUE THREAD

**Issue by stefankp** [primer/brand#123]
The API for `Hero`, `River` and `FAQ` components is very different at the moment. We should strive for a common way of doing things. 

It's a mix of this. 

```jsx
<Component heading="..." />

<Component>
  <Heading>...</Heading>
</Component>

<Component>
  <Component.Heading>...</Component.Heading>
</Component>
```

### Current Hero

```jsx
<Hero
  heading="This is my super sweet hero heading"
  description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sapien sit ullamcorper id. Aliquam luctus sed turpis felis nam pulvinar risus elementum."
  primaryAction={{
    text: 'Primary action',
    href: '#',
  }}
  secondaryAction={{
    text: 'Secondary action',
    href: '#',
  }}
  align="center"
/>
```

### Current River

> They can be composed in any order, but their rendered output will always be in the in the predetermined order.

This API suggests to me that I could pass in more than one `<Text />` component (or other), but actually only the first one is accepted. If we control the allowed number of components and the order, there is no reason to declare `River.Content`.

```jsx
<River>
  <River.Visual>
    <img
      src="https://via.placeholder.com/600x400/f5f5f5/f5f5f5.png"
      alt="placeholder, blank area with an off-white background color"
    />
  </River.Visual>
  <River.Content>
    <Heading>Heading</Heading>
    <Text>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sapien sit
      ullamcorper id. Aliquam luctus sed turpis felis nam pulvinar risus
      elementum.
    </Text>
    <Link href="#">Call to action</Link>
  </River.Content>
</River>
```

### Current FAQ

```jsx
<FAQ>
  <FAQ.Heading>Frequently asked questions</FAQ.Heading>
  <FAQ.Item>
    <FAQ.Question>
      What&apos;s included in the GitHub for Startups offer?
    </FAQ.Question>
    <FAQ.Answer>
      <p>
        All GitHub for Startups companies receive up to 20 seats of GitHub
        Enterprise for free for year one and 50% off year two. Learn more
        about the features and capabilities of GitHub Enterprise{' '}
        <InlineLink
          href="https://www.github.com"
          target="_blank"
          rel="noreferrer"
        >
          here
        </InlineLink>
        .
      </p>
    </FAQ.Answer>
  </FAQ.Item>
</FAQ>
```

**Comment by rezrah** [comment]
Next steps: 

- Await feedback from @stefankp et al
- Document API conventions and rationales in an ADR

**Comment by stefankp** [comment]
@rezrah I think we should prefer the composable APIs when possible. Exception could be when a component only has required inputs. Looking forward to the Hero refactor 👌

**Comment by rezrah** [comment]
Closing this issue as..

- A revised hero has now shipped with a composable API 
- We'll be writing up the ADR in contributor documentation in Q1
- We already have established precedent for writing composable component API's, which is being used in all net new components.
