### ISSUE TITLE
Add presets for granular control over font widths, weight and slant in Heading component

### ISSUE THREAD

**Issue by rezrah** [primer/brand#175]
With Mona Sans, we can now offer granular control over typographic visual appearance. 

E.g.

![variable font usage for mona sans](https://user-images.githubusercontent.com/13340707/216657529-e0b75c97-39d9-411c-a49e-87a2bf9242c9.png)

- Could `Heading` support some 'presets' or official variants at a system / library level?
- Should we provide a clean API to allow users to experiment more easily with the font?
- What is the recommended approach for leveraging in Primer Brand?

**Comment by rezrah** [comment]
Closed by https://github.com/primer/brand/pull/186

Slant customisation not required for time being.

**Comment by samoshin** [comment]
legend ⚡ @rezrah !
