### ISSUE TITLE
[BUG - React] - SubdomainNavBar blur not filling entire width of header

### ISSUE THREAD

**Issue by rezrah** [primer/brand#207]
Example: 

https://user-images.githubusercontent.com/13340707/224756667-b9a2f9db-a8dd-431d-bc57-53a50e5cb528.mov

Steps to reproduce:

1. Go to https://galaxy.github.com/
2. Resize viewport to make it smaller
3. Notice the blur is not filling the width

**Comment by MadMango** [comment]
Is this still an issue? I just had a look now, seems okay.

**Comment by stamat** [comment]
@rezrah @raytalks folks, this is old news. The site was redesinged and redeveloped, so I've heard by @simurai! Amazing work dude!!! ✨ 

This design from the video is Galaxy from the time when I left GH... 2023. And now we have 2024 design.

I was hoping to tackle this simple task right away, but with heavy heart I'm closing this issue...

**Comment by rezrah** [comment]
👋 @stamat thanks for the update. The repro steps are out of date as you said, but I think the underlying issue still needs to be resolved as it's a bug in the SubdomainNavBar component. Should be reproducible in Storybook, I think.

**Comment by rezrah** [comment]
🙌 That's great, thanks for double-checking this @stamat... 🙇 

Let's close this issue for now 👍
