### ISSUE TITLE
Set list-style-position to inside

### ISSUE THREAD

**Issue by stefankp** [primer/brand#230]
Can we ensure `ul` and `ol` use `list-style-position: inside;` in the FAQs? 

### Before

<img width="858" alt="image" src="https://user-images.githubusercontent.com/3661203/231471128-0e8e3d68-7abd-4e5e-bce9-349d6e628916.png">

### After

<img width="841" alt="image" src="https://user-images.githubusercontent.com/3661203/231471283-89ee5fd2-d449-49f4-8f82-5cdf4b783794.png">

**Comment by rezrah** [comment]
👋 Could you share a repro example for the before screenshot please?

I'm looking in our Storybook, and I can't reproduce this. 

Also, have you tried using [UnorderedList](https://primer.style/brand/components/UnorderedList)? Wondering if it works better for you.

**Comment by sergioalvz** [comment]
@stefankp, I have a working branch that replaces default `ul`/`ol` lists with their Primer Brand counterparts for this (and similar) pages. I'm tagging you in the pull request to discuss it further. I think that would be a better-suited solution.
