### ISSUE TITLE
Make SubdomainNavBar children optional

### ISSUE THREAD

**Issue by stefankp** [primer/brand#231]
Some of the pages we build on resources.github.com are meant for campaigns only. Ideally, these pages minimize links to focus visitors on single CTAs. Could we make children for https://primer.style/brand/components/SubdomainNavBar optional, so that we can render it with just the GitHub logo and subdomain name?

**Comment by rezrah** [comment]
👋 Thanks for bringing this up. 

- The GitHub logomark typically goes back to the github.com homepage, indicated by an arrow hover effect. Will this behave more like a document root link now? So if used on resources.github.com, it will go to `/` and we remove the hover effect?
- The buttons are already optional, so can work for both of your scenario's @stefankp @waynewi 

 also cc. @ajashams @samoshin @danielguillan for confirmation that we can use the SubdomainNavBar pattern in this way for non-flagship marketing pages.

**Comment by stefankp** [comment]
> The GitHub logomark typically goes back to the github.com homepage, indicated by an arrow hover effect. Will this behave more like a document root link now? So if used on resources.github.com, it will go to / and we remove the hover effect?

@waynewi that's for you to decide.

> The buttons are already optional

Ah awesome 👌

**Comment by ajashams** [comment]
This request sounds reasonable to me. I prefer that we stay consistent and continue to route customers to our /home page when they click the GitHub logo. Otherwise, let's use the / Resources header if that's the intention.

**Comment by rezrah** [comment]
Thanks @ajashams - one last thing, is it okay to show the logomark without adjacent text in the [SubdomainNavBar](https://primer.style/brand/components/SubdomainNavBar)? 

We weren't sure if this was an officially supported pattern, as the component will typically display contextual text alongside it separated by a forward slash. E.g.

![Screenshot 2023-04-18 at 10 16 56](https://user-images.githubusercontent.com/13340707/232732304-3fb95077-1082-4b28-8c8d-339785d1d16a.png)

If it's okay to use the SubdomainNavBar without title text, we would need to do some minor refactoring to React component to remove the slash, but we'll wait on the answer to the question above..

**Comment by rezrah** [comment]
It's in our inbox, so it's scheduled to be discussed at the next planning call on Monday. 👍 We can ship the update to the component next week, or do you need it sooner @waynewi.

**Comment by rezrah** [comment]
> Just want to make sure but I do not see any CTA buttons on the right hand side and want to ensure that when it's time to build this in Contentful, it will be clear to the Engineer that it's okay to have CTA buttons.

👍 The buttons still work as usual, and are already optional. No extra work needed to make it work.

Here's an example of how it would all work together:

![Screenshot 2023-04-27 at 17 42 38](https://user-images.githubusercontent.com/13340707/234932247-b719dd96-6900-4ce0-9b7e-dcffa8b95321.png)

**Comment by rezrah** [comment]
@waynewi - FYI this feature has shipped in Primer Brand `v0.17.1`.

E.g.

https://user-images.githubusercontent.com/13340707/235921137-bad21598-f787-4f7c-8ce5-c2da645e2d70.mov
