### ISSUE TITLE
Apply `text-decoration:none` also to the `:hover` state

### ISSUE THREAD

**Issue by sergioalvz** [primer/brand#247]
Components that may also serve as links (such as [`Button`](https://github.com/primer/brand/blob/6d590e2994398caceee5731a2f59e13d108f2b9e/packages/react/src/Button/Button.module.css#L8) or [`InlineLink`](https://github.com/primer/brand/blob/6d590e2994398caceee5731a2f59e13d108f2b9e/packages/react/src/InlineLink/InlineLink.module.css#L2)) have `text-decoration:none` rules only applied to their normal state. This can create conflicts when sites use a stylesheet that explicitly sets `text-decoration:underline` for `a:hover` (for example, for accessibility reasons). 

I think adding `text-decoration:none` to the `:hover` state would fix the problem.

![Screenshot 2023-04-25 at 16 32 15](https://user-images.githubusercontent.com/3042654/234310912-c97f7f40-d9d6-4782-8838-2eb553936d5d.png)

**Comment by JoshBowdenConcepts** [comment]
Hey @sergioalvz, how would you feel about creating a stylesheet that overwrites these changes? My only concern is that I wouldn't want Brand to take on a number of these kinds of changes creating a system that is too rigid requiring overrides.

Maybe this specific case is an outlier though, I am not sure. What do you think?

**Comment by rezrah** [comment]
👋 @JoshBowdenConcepts, FYI we've already agreed to apply this change to Primer Brand. The proposed solution should be valid, but you may need to verify it doesn't cause any regressions. In this case, it's not so much an override, but a missing feature.
