### ISSUE TITLE
Inconsistent outer spacing between components

### ISSUE THREAD

**Issue by sergioalvz** [primer/brand#248]
Hey folks :wave:,

I see there are some inconsistencies in components about horizontal spacing. That's especially noticeable when looking at components in narrow screen sizes. For example, the `SectionIntro` component uses a `padding-block` property that makes it have some horizontal space in narrow screens, while the `River` or the `FAQ`, for example, will be touching the screen's borders. 

Right now, I'm applying some custom padding for both `River` and `FAQ` to create a consistent experience, but I think it would be great if we could make all components behave the same.

**Comment by josepmartins** [comment]
Adding more examples, this time about vertical spacing:

Slack thread: https://github.slack.com/archives/C04E44ZPNEA/p1683546014522099

**Comment by sergioalvz** [comment]
Adding one more example. The `River` component ensures some outer spacing, but `Testimonial` and `FAQ` components do not work well together without additional CSS:

![Screenshot 2023-05-16 at 11 00 02](https://github.com/primer/brand/assets/3042654/5feb7859-939c-45df-88be-39f3760f05c5)

**Comment by nsolerieu** [comment]
new `flexSection` component aims at addressing this systematically on SWP side so let's redirect the conversation there as we assess the viability of the solution: https://github.com/github/brand-marketing-design/issues/1634
