### ISSUE TITLE
🐛 [BUG] - Grid Column with responsive map is misbehaving

### ISSUE THREAD

**Issue by enstyled** [primer/brand#340]
### Describe the bug

When using the Grid component, some combinations of column spans are not working when set with a responsive map.

### Reproduction steps

This works:
```
<Grid enableOverlay>
  <Grid.Column span={9}>
    ...
  </Grid.Column>
  <Grid.Column span={3}>
    ...
  </Grid.Column>
</Grid>
```

This does not work:
```
<Grid enableOverlay>
  <Grid.Column span={{medium: 9}}>
    ...
  </Grid.Column>
  <Grid.Column span={{medium: 3}}>
    ...
  </Grid.Column>
</Grid>
```

### Expected behavior

When using a responsive map to set the columns spans, the columns should stack as expected.

### Browsers

Chrome

### OS

Mac

**Comment by enstyled** [comment]
Attaching the screenshots here since the form was not allowing uploads 🤷🏼‍♂️

<img width="1326" alt="Screenshot 2023-07-13 at 13 34 29" src="https://github.com/primer/brand/assets/621097/573a325a-0df2-4e21-ae70-a5f53789942f">
![screenshot_2023-07-13_at_13 35 23](https://github.com/primer/brand/assets/621097/1f51d2d9-e484-4eff-b591-ef1df17b14b6)

**Comment by rezrah** [comment]
👍 Thanks @enstyled.

Issue is that we're missing the css styles for columns that span beyond 8 at medium viewport. I'll take a look at fixing this for you.
