### ISSUE TITLE
🐛 [BUG - React] - FormControl.Required not indicated with Checkbox

### ISSUE THREAD

**Issue by philernst** [primer/brand#348]
### Describe the bug

The following snippet (see "required" attribute):

```
<FormControl required>
  <FormControl.Label>Checkbox 1</FormControl.Label>
  <Checkbox name="day" value="" />
</FormControl>
<FormControl>
  <FormControl.Label>Checkbox 2</FormControl.Label>
  <Checkbox name="night" value="" />
</FormControl>
```

Doesn't indicate if the checkbox is required:

<img width="279" alt="Screenshot 2023-07-17 at 9 48 52 AM" src="https://github.com/primer/brand/assets/7658603/6355f781-1ac5-46b0-a51b-225c953edc5b">

### Reproduction steps

```bash
^ Above ^
```

### Expected behavior

```bash
* is added to the checkbox title when it's required. Similar to the other fields here: https://primer.style/brand/storybook/?path=/story/components-forms-examples--git-hub-enterprise
```

### Screenshots

```bash
^ Above ^
```

### Browsers

Chrome

### OS

Mac

**Comment by mperrotti** [comment]
@philernst @rezrah - this is intentional. A single checkbox cannot be required because both checked (`true`) and unchecked (`false`) are valid values.

**Comment by mperrotti** [comment]
If you want indicate that a selection must be made in a group of checkboxes, it should be indicated for that whole group of checkboxes. Here's an example from @primer/react: https://primer.style/react/storybook/?path=/story/components-checkboxgroup--playground&args=required:!true

**Comment by philernst** [comment]
@mperrotti Got it. The use case I was thinking about is where the submitter is required to check the checkbox to submit the form. For example:

<img width="606" alt="Screenshot 2023-07-21 at 11 06 33 AM" src="https://github.com/primer/brand/assets/7658603/b66fd24d-aae2-4ebe-a462-77f19de4f17c">


I suppose in that situation a `CheckboxGroup` would need to be added to indicate that the field is required to be `true` to submit the form.

**Comment by mperrotti** [comment]
@philernst - I'm not sure we even need a required indicator on that one. I think it would be ok to just return a validation error if it isn't checked.
