### ISSUE TITLE
[Accessibility] After resizing page to 320*256 focus moving to the hidden elements while navigating with the tab key.

### ISSUE THREAD

**Issue by enstyled** [primer/brand#386]
As described in https://github.com/github/accessibility-audits/issues/5262

> Users with low vision who find it difficult to read the text in small font uses enlarged text with re-size, will be impacted as at 400% zoom and users will be confused if the focus move to hidden element while using keyboard tab key.

**Comment by simurai** [comment]
For now [the title is a bit smaller](https://github.com/github/githubuniverse.com/pull/1798) below `390px` viewport width:

Before | After
--- | --- 
![kebab button is hidden](https://github.com/github/githubuniverse.com/assets/378023/770e9342-cd08-4f35-a5cb-23efe81e461e) | ![kebab button is visible](https://github.com/github/githubuniverse.com/assets/378023/926be0e7-f208-492f-91b7-be0827c90a6b)

But it's a pretty custom fix.

**Comment by rezrah** [comment]
Related to https://github.com/primer/brand/issues/514

**Comment by rfearing** [comment]
@rezrah I played around with this in [Storybook](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-subdomainnavbar--playground) and I believe this can be closed now 🎉
