### ISSUE TITLE
[Accessibility] Visual name and aria-label are different for 'GitHub' control

### ISSUE THREAD

**Issue by enstyled** [primer/brand#387]
As described in https://github.com/github/accessibility-audits/issues/5252

> Users who rely on screen readers will get impacted, if the visual name and aria-label are different for a control. The users will not get the exact information about the control and may miss the functionality.

**Comment by simurai** [comment]
Here I'm actually not sure, because the current longer `Go to GitHub Homepage` should help in clarifying what happens when clicking the link. I brought that up in the [original issue](https://github.com/github/accessibility-audits/issues/5252#issuecomment-1664845314).
