### ISSUE TITLE
🐛 [BUG] - Spacing on River Breakout

### ISSUE THREAD

**Issue by jesussandreas** [primer/brand#419]
### Describe the bug

Currently it's 48px.

![Image](https://github.com/primer/brand/assets/26472012/30072d27-b867-4e22-bac3-2cef496b10a6)

---

Should be 64px total.

![Image](https://github.com/primer/brand/assets/26472012/982ae7a1-1e7b-47ef-8528-cb736c8abc0b)

### Reproduction steps

1. Go to 'https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-riverbreakout--default'
2. Measure the spacing

### Expected behavior

64px.

### Browsers

Chrome

### OS

Mac

**Comment by josepmartins** [comment]
hey @jesussandreas, thanks for the issue. What should we use for tablet and mobile devices? Current values are:

- 48px large screens
- 36px tablet
- 24px mobile

**Comment by jesussandreas** [comment]
Hey @josepmartins,

I think the scale should be the following: Desktop 64px, Tablet 48px, Mobile 40px.

**Comment by josepmartins** [comment]
Closing as fixed here https://github.com/github/primer/issues/2641
