### ISSUE TITLE
[Feature request] Add support for multiple `AnchorNav.Action`

### ISSUE THREAD

**Issue by simurai** [primer/brand#452]
[This came up](https://github.slack.com/archives/C05SLBP176W/p1696317545767589) when starting with the Copilot implementation.

## Current state

[`AnchorNav`](https://primer.style/brand/components/AnchorNav) only supports a single `AnchorNav.Action`:

![Image](https://github.com/primer/brand/assets/378023/1f1bd150-bd71-42e4-a326-d47d3fb77fb5)

## Feature request

In [Figma](https://www.figma.com/file/F23I0AtdY5klRhEqfodX2y/Copilot-LP-Refresh?node-id=1118%3A24406&mode=dev) we would like the navigation to have 2 `AnchorNav.Action`.

![Image](https://github.com/primer/brand/assets/378023/0e7e1ef2-1c17-4be7-b8b3-bac84acbe15a)

I guess it's similar to how [`SubdomainNavBar`](https://primer.style/brand/components/SubdomainNavBar) can have a "Primary" and a "Secondary" action.

## Current workarounds

For now, the "Compare plans" is moved to a `AnchorNav.Link`. IMO that's the better option in this specific case since we do have a "Pricing" section, so it would be odd if it's not part of the "normal" navigation. But even if we would go with this for Copilot, the need for a Primary and Secondary action will probably come up again sooner or later.

![Image](https://github.com/primer/brand/assets/378023/87ed7aff-7a80-4776-93ef-4fc639c64c46)

Another option might be add 2 `AnchorNav.Action` (which works), and then add some custom styling to make it appear like a primary button. But that's more an emergency hack and shouldn't be kept long term.

/cc @jesussandreas @ajashams

**Comment by joseph-lozano** [comment]
@rezrah should #498 close this?

**Comment by joseph-lozano** [comment]
Closed by #498

**Comment by rezrah** [comment]
@joseph-lozano that's correct. Thanks for following up.

@simurai - documentation for the secondary action is here: https://primer.style/brand/components/AnchorNav#secondary-action
