### ISSUE TITLE
🐛 [BUG] - Button Gap on Medium Size should be 4px (0.25rem) instead of 12px.

### ISSUE THREAD

**Issue by jesussandreas** [primer/brand#504]
### Describe the bug

Per designs, we have 4px between text and label. Currently is set to 12px.

Per design.

![Image](https://github.com/primer/brand/assets/26472012/1ea02ce6-4ba5-4e34-8ca4-9602feb2c55e)

Vs.

Live.

![Image](https://github.com/primer/brand/assets/26472012/f08550ed-7ff4-419c-8445-ce20c51d7014)

### Reproduction steps

Go to storybook and inspect elements.

### Expected behavior

4px (Gap)

### Screenshots

Included above

**Comment by auareyou** [comment]
Hi 👋  May I ask why we are making this change? Would love to understand where it's coming from. Thank you 🙏

**Comment by jesussandreas** [comment]
Hi @auareyou, we originally designed them with the gap being `4px`, so just going back to it.

I think the spacing was larger because we were baking in some of the spacing inside the icons into the gap, but it was not working so reverting that.

**Comment by rezrah** [comment]
👋 @jesussandreas - thanks for clarifying. This request was reviewed at the last Primer Brand Office Hours. 

It seems like there's [optical alignment](https://github.com/primer/brand/blob/11e6ab1c050e9963c5d1cf7686b04e55f2718dee/packages/react/src/Button/Button.module.css#L51) being applied to the icon, which gives the impression that there's a 12px gap when it's actually 4px already.  

We agreed this felt like indirection, and could consider removing this. Before we do that, however...

@langermank - Do you have any context on [this CSS](https://github.com/primer/brand/blob/11e6ab1c050e9963c5d1cf7686b04e55f2718dee/packages/react/src/Button/Button.module.css#L51), and have thoughts on whether we can remove this? I can see that the medium control token applies 12px gap, so this could be a case of creating a new token value with a smaller value and removing the optical alignment. If this sounds reasonable to you, here's what the before/after's would look like...

<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">



![Image](https://github.com/primer/brand/assets/13340707/8712b202-b87a-4a68-bc19-f53ad4dc5642)



 </td>
<td valign="top">



![Image](https://github.com/primer/brand/assets/13340707/4e59eb56-0cfa-4ce6-83f2-3b849d5bea2d)



</td>
</tr>
</table>

cc. @danielguillan

**Comment by raytalks** [comment]
@langermank 👋 Do you have any thoughts on this? 👆

**Comment by rezrah** [comment]
@raytalks @jesussandreas - apologies, forgot to update this issue.

I discussed this with @langermank and we're not planning to make changes to the component at this point.. reasons being:

- The visual gap is already 4px
- We use optical alignment (as [previously mentioned](https://github.com/primer/brand/issues/504#issuecomment-1904050518)) to offset the animated stem in the chevron. This makes it appear like there's a 12px gap in the inspector, but there actually isn't one. 
- There's admittedly some indirection here (which caught us out while triaging this request), but it's not something that we feel is necessary or urgent to change right now given there will be no visual change, and factoring in the risk of regressions.

Hope this makes sense. Closing this issue for now, but feel free to reopen if anyone feels there's something we've missed.
