### ISSUE TITLE
🐛 [BUG] - `padding-inline-start` does not set in Timeline.Item component

### ISSUE THREAD

**Issue by alphonsotran** [primer/brand#509]
### Describe the bug

Tested in the `github/github` app with both of these versions: 
`@primer/react-brand: "0.28.1"` (current)
`@primer/react-brand: "0.30.0"`(latest)

Hey all 👋 I may have found a style bug when using the [Timeline](https://primer.style/brand/components/Timeline) component that is present in the landing-pages on dotcom. Both by itself as a component and in the [River Breakout's](https://primer.style/brand/components/River/react#river-breakout) `trailingComponent` prop, the text overlaps with the bullets.

<details><summary>Visual bug in the River Breakout and Timeline component </summary>
<p>

![Image](https://github.com/primer/brand/assets/27393694/6fb289c7-446d-4455-a4b1-748dbc1b0b37)

</p>
</details> 

After doing a quick investigation, I found that the `padding-inline-start` property wasn't being set for the `Timeline.Item` child component. This property wasn't missing in storybook version. 

<details><summary>Timeline item with `padding-inline-start` missing in dotcom's landing-pages</summary>
<p>

![Image](https://github.com/primer/brand/assets/27393694/302893ea-ee9c-4d7a-b4cb-fb82af0480d1)

</p>
</details> 

<details><summary>Timeline item with `padding-inline-start` in storybook</summary>
<p>

![Image](https://github.com/primer/brand/assets/27393694/77e97147-6b6b-4b6c-942e-7a41f748750b)

</p>
</details> 

I was able to fix this if I added the property `dir=ltr` attribute in the `<Timeline />` component, but I believe this is meant to be closed off and for internal use only since typescript yells about it. 

### Browsers

Chrome, Firefox, Safari

### OS

Mac

**Comment by rezrah** [comment]
👋 @alphonsotran - A global `dir` attribute needs to be set on your page for our [logical css properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values) to display correctly. I'd recommend setting this as high as possible in the DOM, ideally `html`. 

E.g.

![Image](https://github.com/primer/brand/assets/13340707/8ee022d2-bb09-4400-81dd-2d0ff88f01f9)

Primer Brand uses prepended dir values in its selectors, so setting the reading direction attribute should fix the issues you're seeing 🤞.
