### ISSUE TITLE
[Accessibility] `SubdomainNavBar` misses controls when narrow

### ISSUE THREAD

**Issue by simurai** [primer/brand#514]
This came up in the https://githubuniverse.com accessibility audit:

- https://github.com/github/accessibility-audits/issues/7085
- https://github.com/github/accessibility-audits/issues/7084

## Problem 1

When using no `<SubdomainNavBar.Link>`, but only a `<SubdomainNavBar.SecondaryAction>`, on narrow viewports the hamburger menu button (to access the `<SubdomainNavBar.SecondaryAction>`) is missing.

```jsx
<SubdomainNavBar title="GitHub Universe">
  <SubdomainNavBar.SecondaryAction href="#">
    Watch on demand
  </SubdomainNavBar.SecondaryAction>
</SubdomainNavBar>
```

Wide viewport | Narrow viewport
--- | ---
![Button is visible on wide viewport](https://github.com/primer/brand/assets/378023/4d3e6b27-3988-4af5-8137-82ca46f5063c) | ![Menu button is missing on narrow viewport](https://github.com/primer/brand/assets/378023/b8b2031f-3ecb-4496-9757-025c0dd12788)

## Problem 2

With a viewport of `320x256` the `title` (Home) link should still be visible.

Wide viewport | `320x256` viewport
--- | ---
![Title link is visible on wide viewport](https://github.com/primer/brand/assets/378023/4d3e6b27-3988-4af5-8137-82ca46f5063c) | ![Title link is missing on narrow viewport](https://github.com/primer/brand/assets/378023/36c259e1-eaaa-414b-8079-99b26701dd2b)

This one is probably trickier to fix. [Rainfocus](https://reg.githubuniverse.com/flow/github/universe23/sessioncatalog/page/sessioncatalog?search.deliveryformat=1692799009854004CQlx) changes the font-size and then even wraps onto multiple lines:

https://github.com/primer/brand/assets/378023/0d0a8ba1-95ab-47de-ad74-21b6715c69de

But that's harder to do on the component level when the length of the title is unknown and could make design "suffer". An alternative might be to move the `title` link as the first item in the "overflow menu":

Wide viewport | `320x256` viewport
--- | ---
![Title link is visible on wide viewport](https://github.com/primer/brand/assets/378023/69185e35-0976-4d09-97fb-b79d710eb11d) | ![Title link is in the menu on narrow viewport](https://github.com/primer/brand/assets/378023/ab067dbb-d922-4916-8b2a-05c94d959f9c)

**Comment by rezrah** [comment]
Hey @simurai 👋 

### Problem 1

> When using no <SubdomainNavBar.Link>, but only a <SubdomainNavBar.SecondaryAction>, on narrow viewports the hamburger menu button (to access the <SubdomainNavBar.SecondaryAction>) is missing.

Thanks for flagging. Burger menu button currently only appears when links are present. We can update to include both primary and secondary actions.

Next steps:

- Update SubdomainNavBar burger menu visibility logic to include CTAs
- Design review for location of buttons, which would appear at the bottom of an otherwise empty menu

### Problem 2

> With a viewport of 320x256 the title (Home) link should still be visible.

This was an intentional design choice. [We even encourage use of our nav bar without the header in some cases.](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-subdomainnavbar--no-title). Wonder if we could use an aria-label or similar to convey this information instead 🤔 We can check in with a11y team on next steps to remediate this one. Thanks for flagging.

**Comment by simurai** [comment]
> Wonder if we could use an aria-label or similar to convey this information instead

How I understood https://github.com/github/accessibility-audits/issues/7085, using `aria-label` wouldn't resolve the issue, since it's not screen reader related.

> they will not be able to know the disappeared contents present on the page due to which they will miss the information, which can block their further actions.

I _think_ the issue is that **if** we show some information to desktop users, mobile users should have access to the **same** information. So if desktop users see the subdomain, then mobile should also have a way to see the subdomain. One might can try to argue that the subdomain is "non-essential" or "decorative", but not sure if that's acceptable in this case.

The only two options I can think of:

### Option A

Remove the subdomain (`GitHub Universe`) altogether (for desktop + mobile). Pages will need another way to communicate that.

Wide viewport | Narrow viewport
--- | ---
![Subdomain is missing on desktop](https://github.com/primer/brand/assets/378023/40790f2e-4ac4-4a24-9c47-e01fb185bbef) | ![Subdomain is missing on desktop](https://github.com/primer/brand/assets/378023/d6f3214f-5d78-4d49-bf70-e80357d51216)


### Option B

Move the subdomain (`GitHub Universe`) into the hamburger menu as the first item. It won't initially be visible on mobile, but can still be accessed when opening the hamburger menu.

Wide viewport | Narrow viewport | Narrow viewport (menu open)
--- | --- | ---
![Subdomain is visible on desktop](https://github.com/primer/brand/assets/378023/513cec5f-29ac-4c85-8d2e-4cbd295d5344) | ![Subdomain is collapsed on mobile](https://github.com/primer/brand/assets/378023/dff51cd7-9133-4d7a-a47a-f8cb17b89ca6) | ![Subdomain is visible in menu on mobile](https://github.com/primer/brand/assets/378023/c87c8ddd-6693-41bb-88f1-e3c2a3f02600)

Personally I would go with option B since having the subdomain is quite nice. I'll ping the accessibility team to verify if that's ok, or if there is another way to resolve this issue.

**Comment by simurai** [comment]
From https://github.com/github/accessibility-audits/issues/7085#issuecomment-1870652455

> the audit issue isn't about conveying info to screen reader users, it's about ensuring people who magnify their screen (and people on mobile) don't have interactive controls vanish on them. As long as they can still get to the controls on the same page through standard navigation/interaction mechanisms, that fixes the problem.

So yes, option B would fix the issue by moving the title/subdomain (`GitHub Universe`) into the hamburger menu.
