### ISSUE TITLE
🐛 [BUG] - `Testimonial`: insufficient contrast for default quote symbol in dark mode

### ISSUE THREAD

**Issue by sergioalvz** [primer/brand#521]
### Describe the bug

In the `Testimonial` component, when the `quoteMarkColor` is set to `default`, it utilizes a black quote symbol. While this works well in the light theme, it poses a legibility issue in dark mode due to the lack of sufficient contrast.

![Screenshot of a testimonial component in dark mode](https://github.com/primer/brand/assets/3042654/ee06328b-850a-47a7-ae34-0e8984b0a03d)

### Reproduction steps

https://codepen.io/sergioalvz/pen/ExGrxXb

### Expected behavior

Primer Brand provides high-contrast color values for the default quote mark color, ensuring visibility and readability in both light and dark themes.

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by danielguillan** [comment]
Thanks for submitting this bug report, @sergioalvz. There's a fix coming in #532 and will ship in the upcoming release.
