### ISSUE TITLE
[Feature request] Allow custom icon in `UnorderedList.Item`

### ISSUE THREAD

**Issue by simurai** [primer/brand#527]
## Request

For an upcoming project ([internal link](https://www.figma.com/file/VgxWQMaCZ7jUKTSfd5bHje/Security-Assets?type=design&node-id=32-4189&mode=design&t=HZ2w4lOCl6ZQilnK-0)), the design requires a "features list" where some items should have a ✔ check icon, but then some others an ❌ icon .

![Image](https://github.com/primer/brand/assets/378023/4f4e08fd-a6f0-4974-a842-89f5148080e4)

But currently, the [`<UnorderedList>`](https://primer.style/brand/components/UnorderedList/react#checked-variant) component only allows a `checked` variant.

### Option 1

An option would be to add another `variant="excluded"` and then stack two `<UnorderedList>`s. E.g.

```JSX
<UnorderedList variant="checked">
  <UnorderedList.Item>Item 1</UnorderedList.Item>
  <UnorderedList.Item>Item 2</UnorderedList.Item>
</UnorderedList>
<UnorderedList variant="excluded">
  <UnorderedList.Item>Item 3</UnorderedList.Item>
  <UnorderedList.Item>Item 4</UnorderedList.Item>
</UnorderedList>
```

### Option 2

Or each `<UnorderedList.Item>` can be overridden independently:

```JSX
<UnorderedList variant="checked">
  <UnorderedList.Item>Item 1</UnorderedList.Item>
  <UnorderedList.Item>Item 2</UnorderedList.Item>
  <UnorderedList.Item variant="excluded">Item 3</UnorderedList.Item>
  <UnorderedList.Item variant="excluded">Item 4</UnorderedList.Item>
</UnorderedList>
```

### Option 3

Or to be super flexible, each`<UnorderedList.Item>` can be used with any icon (similar to [Leading visual](https://primer.style/brand/components/Label/react#leading-visual) in Labels):

```JSX
<UnorderedList variant="checked">
  <UnorderedList.Item>Item 1</UnorderedList.Item>
  <UnorderedList.Item>Item 2</UnorderedList.Item>
  <UnorderedList.Item leadingVisual={<XIcon />}>Item 3</UnorderedList.Item>
  <UnorderedList.Item leadingVisual={<StarIcon />}>Item 4</UnorderedList.Item>
</UnorderedList>
```

## Urgency

Not 100% sure if this design is final and the planed launch date is in 3 weeks. For now I can just recreate the `<UnorderedList>` or hack the icon into the `<UnorderedList.Item>`, but eventually might be nice to have have native support?

**Comment by rezrah** [comment]
This request was triaged by Primer Brand maintainers, and decision was made to implement option 1 as the preferred API, due to its intrinsic guardrails. Option 3 will also be implemented as an escape hatch, but may not be publicised in the documentation.
