### ISSUE TITLE
🐛 [BUG] - Action menu overlay for adding language dropdown

### ISSUE THREAD

**Issue by loc4all-clover** [primer/brand#540]
### Describe the bug

Hi, we'd like help to change the action menu overlay to allow for addition of a language dropdown on our footer for Resource Hub localization.
We researched how we'd like this feature to look in this [Issue](https://github.com/github/marketing-platform-services/issues/1525#issuecomment-1863320218). We've since decided to move it to the footer but need help to accommodate it. 

### Reproduction steps

Please reference slack thread for the video: https://github.slack.com/archives/C03FY9G00NS/p1708578782973499

### Expected behavior

Would need space to add a language dropdown

### Screenshots

![Screenshot of language dropdown lacking room for footer](https://github.com/primer/brand/assets/118561802/3b9bd1f4-deb0-4974-b73a-5fc6adfa9f64)

### Browsers

Chrome

### OS

Mac

**Comment by rezrah** [comment]
👋 Thanks for opening this issue @loc4all-clover.

We've triaged the request, here are the next steps:

- We'll update ActionMenu component to support a smaller size, which enables more convenient placement into space-constrained locations like that shown in the video.
- We'll increase the number of anchored overlay positions, to allow for the menu to appear above the button where needed.
- @danielguillan will take point on design, and updates to the Figma component.
- I'll make the updates to the React component and documentation.

Let us know if there's anything else we need to consider, or missed. 

We'll also share updates with you through this issue, including potential release dates after we dive into the details a bit moremore.

cc. @raytalks @egim
