### ISSUE TITLE
[Feature request] Support `<Button>` in `RiverBreakout.Content`

### ISSUE THREAD

**Issue by simurai** [primer/brand#565]
## Problem

Currently `RiverBreakout.Content` only supports [Label](https://primer.style/brand/components/Label), [Text](https://primer.style/brand/components/Text),[Heading](https://primer.style/brand/components/Heading), [Link](https://primer.style/brand/components/Link) as children.

For an [upcoming project](https://www.figma.com/file/9OIAJdau1ckwnOpNUdBoiq?type=design&node-id=733-1756&mode=design#752910720) (internal), instead of using a `<Link>`:

![Image](https://github.com/primer/brand/assets/378023/ec26764c-80d1-4fe5-9151-9f36951ccef7)

... we'd like to use a `<Button>` instead, so that the action is a bit more prominent (with a border).

## Possible solution

Also allow `<Button>` in `RiverBreakout.Content` and probably `River.Content` too.

## Urgency

Launch date would be **April 16th**, but might not be a huge blocker. Currently a `<Link>` is used.

**Comment by rezrah** [comment]
👋 Hey @simurai... the River isn't intended to support a button, so this is by-design ([link](https://primer.style/brand/components/River#link)). If I recall correctly, this is to discourage stacking multiple buttons throughout the page. I'd recommend first seeing if we can use the link, and if not, you'd likely need to apply a custom button just after the breakout. 

Looping in @simmonsjenna as our Site Design FR to confirm. Ideally we would help to amend the working design, or put a modification request in to River generally if we're changing our stance on buttons in River.

Also cc'ing @ajashams and @danielguillan for visibility.

**Comment by nsolerieu** [comment]
I support @rezrah suggestion to update the design a not amend the component. The initial intention to NOt enable too many CTA on a page is stronger than the one-off need here


Here is the Universe24 section with the standard link

![Image](https://github.com/primer/brand/assets/10632534/ffad57ca-90f5-456e-9790-54de6ee7c427)

**Comment by rezrah** [comment]
Thanks @nsolerieu @simmonsjenna 👍 

FWIW we also have a large size for the Link component, if we need to draw extra attention to it: [Storybook](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-link-features--large)

**Comment by simurai** [comment]
Ok, thanks everyone for considering it. Found a [workaround](https://github.com/github/githubuniverse.com/blob/3cbac57949091216f99f3fac6e704e68e93e4ada/components/CallForSpeakers/CallForSpeakers.tsx#L40-L44), that might be ok for this one-off. Don't patch it. 😉

**Comment by ajashams** [comment]
@simurai I believe your workaround solves for this, but I'd like to keep the `secondary button` here for Universe because it's our secondary CTA on the page. **This is an edge case for this experience** that I don't want to encourage, per @nsolerieu 's comment about exposing too many buttons on the page. However, I don't think it makes sense for us to use a button for this same action in the hero and then change it to a link when its repeated further down the page. 

I am curious if/how we make exceptions for scenarios when components _**repeat**_ `primary` and `secondary buttons` from the hero on the page.
