### ISSUE TITLE
🐛 [BUG] - `SubNav.Link` marked as current when `aria-current="false"`

### ISSUE THREAD

**Issue by sergioalvz** [primer/brand#572]
### Describe the bug

Version `0.32.0` of `@primer/react-brand` incorrectly marks `SubNav.Link` items as "current" when using `aria-current="false"`. According to MDN, [`false`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current#false) is a valid value for this attribute.

Currently, the styling for `SubNav.Link` is activated by the mere presence of the `aria-current` attribute, rather than by its actual value.

https://github.com/primer/brand/blob/eaeb50e31e87748c7d1aadcdfa9518c28ee31765/packages/react/src/SubNav/SubNav.module.css#L183-L186

### Reproduction steps

https://codepen.io/sergioalvz/pen/rNbrbae

### Expected behavior

Only elements with `aria-current="page"` or `aria-current="true"` are marked as current

**Comment by MelissaPastore** [comment]
Closing this out since it was fixed in https://github.com/primer/brand/pull/585.
