### ISSUE TITLE
🐛 [BUG] - `SubdomainNavBar` has wrapping/overflow issues

### ISSUE THREAD

**Issue by simurai** [primer/brand#581]
### Describe the bug

Reported [here](https://github.com/orgs/github/projects/9798/views/1?pane=issue&itemId=60907709) (internal). When resizing the browser window to around `930px`, it can cause wrapping/overflow issues when there are multiple CTA buttons with multi-word text labels.

### Reproduction steps

1. Go to https://github-2c2fbb9b0f-1106639.drafts.github.io/ (internal)
2. Scroll down a bit (until CTAs appear)
3. Resize browser window to around `930px`
4. Notice wrapping/overflow issues

### Expected behavior

1. Go to https://github-2c2fbb9b0f-1106639.drafts.github.io/ (internal)
2. Scroll down a bit (until CTAs appear)
3. Resize browser window to around `930px`
4. Button text should not wrap onto multiple lines. Buttons should not overlap links.
### Screenshots

![Image](https://github.com/primer/brand/assets/378023/481be632-2dc4-4abf-b3b8-0817f86bb4ee)

### Browsers

Chrome

### OS

Mac

**Comment by simurai** [comment]
I tried to fix it with `white-space: nowrap;`, but then the buttons get cut-off:

![Image](https://github.com/primer/brand/assets/378023/1722e5d3-e8d2-4149-b54f-4ea897022b34)

And truncation also doesn't really work. I guess it's literally not possible to show everything in the available space. Maybe instead of switching to the "hamburger menu" at `767px`, it could happen earlier, based on the space that is needed. Might not be easy..? Container queries? JS measuring needed width, then switching over? 🤔

**Comment by simurai** [comment]
Ok, as a quick fix, the "Become a speaker" button gets hidden when not enough space (around `1080px`).

**Comment by rezrah** [comment]
Thanks for filing this @simurai ❤ 

Potential solutions:

- Implement small Buttons for consistency with other, newer nav patterns (SubNav)
- Add short title option

We generally discourage long CTA labels anyway, but the above two options might be enough here.
