### ISSUE TITLE
🐛 [BUG] - VideoPlayer documentation and examples not working correctly

### ISSUE THREAD

**Issue by rezrah** [primer/brand#600]
### Describe the bug

Originally reported by @patrickhlauke ([link](https://github.slack.com/archives/CSGAVNZ19/p1717422257166009))

VideoPlayer examples in Storybook and documentation no longer run correctly. Root cause needs investigating and examples should work correctly as per other component documentation pages.

### Reproduction steps

1. Go to https://primer.style/brand/components/VideoPlayer or https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-videoplayer-features--without-branding
2. Click play on the video 
3. Observe that the video does not play

### Expected behavior

Videos and closed captions should play correctly.

### Screenshots

n/a

### Browsers

Chrome

### OS

Mac

**Comment by patrickhlauke** [comment]
In the documentation and storybook, the video element is referencing non-existent `example.mp4` and `example.vtt` files. (for documentation, it points to `https://primer.style/brand/assets/example.mp4` / `https://primer.style/brand/assets/example.vtt`, in storybook it points to the root of the site, so `https://stunning-chainsaw-j82glqz.pages.github.io/example.mp4` and `https://stunning-chainsaw-j82glqz.pages.github.io/example.vtt`).

**Comment by joshfarrant** [comment]
This was fixed in https://github.com/primer/brand/pull/633

**Comment by patrickhlauke** [comment]
Great to see working videos. One minor nitpick: it would be good to have a video with some dialog/spoken words, to then also be able to see captions in action.

**Comment by joshfarrant** [comment]
Great suggestion, thanks @patrickhlauke. I'll see whether we've got any videos with audio+captions that I can slot in too
