### ISSUE TITLE
🐛 [BUG] - `SubNav` heading text breaks line

### ISSUE THREAD

**Issue by stefankp** [primer/brand#602]
### Describe the bug

`SubNav` https://primer.style/brand/components/SubNav heading text breaks onto the next line.

Possibly due to `width: 100%` on `Primer_Brand__SubNav-module__SubNav__links-overlay`. Fixed by replacing with `flex-grow: 1`.

### Reproduction steps

1. Go to https://github.com/social-impact
2. See heading in SubNav on two lines.

### Expected behavior

1. Go to https://github.com/social-impact
2. See heading in SubNav on one line.

### Screenshots

<img width="1727" alt="Screenshot of SubNav on social impact page." src="https://github.com/github/github/assets/3661203/0390f101-d55f-4374-9bab-0b03ed03d7ae">

![SubNav with width CSS attribute](https://github.com/primer/brand/assets/3661203/5d75a225-50f3-4c6b-93ec-9bb1a5d7d461)

![SubNav with flex-grow CSS attribute](https://github.com/primer/brand/assets/3661203/8b3ee7c8-01e9-4bed-bbce-9b882c6b96c7)

### Browsers

Safari

### OS

Mac

**Comment by rezrah** [comment]
@stefankp thanks for opening this bug report 💖 

Issue has been fixed in https://github.com/primer/brand/pull/610, and is currently pending release. You can track release status in [this PR](https://github.com/primer/brand/pull/605), as well as use the RC to verify the fix on your end if needed.

**Comment by stefankp** [comment]
Thank you @rezrah 👏
