### ISSUE TITLE
[Feature Request] Allow Card to span the full width of its container.

### ISSUE THREAD

**Issue by joshvogel17** [primer/brand#603]
**Problem**
Card contained in `Grid.Column` with span={12} is not stretching the entire width of the column. The use case would be viewing the Cards on a tablet where we have changed to span={12} at the xsmall breakpoint. Image of issue:

![Image](https://github.com/primer/brand/assets/103219506/cc071b44-5902-4f0c-b7b5-caedf0c5d5c5)

The current workaround implemented is to center the Cards in this case, but this is a break from design that shows the cards either stretching the entire width of the `Grid` or having span={6}

**Design**
![Image](https://github.com/primer/brand/assets/103219506/a3e7b806-fb0b-4aa1-89cf-14bc57e02e63)

**Workaround**

![Image](https://github.com/primer/brand/assets/103219506/e59a2981-f77b-41fa-83f4-aa74c52e148f)

**Proposal**
Allow users to set the `max-width` of the Card. Use type to control what values users can enter, but include "100%" so users can have the card fill the entire space of the container if need. If no `maxWidth` is set fallback to the `--brand-Card-maxWidth`

![Image](https://github.com/primer/brand/assets/103219506/4183d41e-0cff-4a33-bc88-3dd9c5cb2db2)

**Comment by rezrah** [comment]
@joshvogel17 - thanks for opening this request. A `fullWidth` prop has been added to the Card component to address your requirements. This will be available in the next release.
