### ISSUE TITLE
[Feature Request] Add ability to attach analytics attributes to FAQ tab buttons

### ISSUE THREAD

**Issue by joshvogel17** [primer/brand#612]
**Problem**
We are currently trying to attach analytics attributes to all clickable elements in the SEO templates. While verifying the template, it was noticed the FAQ tab buttons do not have a way to attach analytics to them.

![Image](https://github.com/user-attachments/assets/113b5075-d3f7-42e5-ba9a-94b06f1892c3)

**Comment by joshfarrant** [comment]
Hey @joshvogel17 👋 Thanks for the feature request!

This has been added and will ship in the next Primer Brand release 🚀
