### ISSUE TITLE
[Feature request] Story scroll river

### ISSUE THREAD

**Issue by nsolerieu** [primer/brand#619]
## Problem

As we scale the F2 template we noticed the usage of the river as a primary utility to present value propositions and visuals. The repetition make the page vertical flow very heavy and doesn't offer the variety needed to fit the often large features sets. As we have established a framework to scale our UI demos, we are looking for way to improve the reading/scroll experience for the user and open possibilities for our PMM and Writers.

![Typical page featuring many stacked rivers](https://github.com/user-attachments/assets/4c56047a-9f96-448f-8c64-75c26144d8c4)

## Suggested solution

Adopting an sticky element that update on scroll would allow to extend the scroll narrative while reducing visual load. The visual would sty fixed to the same position while the text update. 

Desktop

https://github.com/user-attachments/assets/21aee994-8461-4a25-8d65-317a358431ad

Mobile

https://github.com/user-attachments/assets/950df1fe-7e4e-49c2-bfa6-c4c68da19a9c

Fallback: static (regular) rivers

## Urgency

This request come from the [solution page template](https://github.com/github/brand-and-marketing-epd/issues/209) project where we are expecting lots of river and complex, industry specific narrative that could use this upgrade. Project is expected to ship mid-late july

**Comment by nsolerieu** [comment]
Here are some additional specification (circa 2023)

These have been reviewed by accessibility:

> In order to accommodate people with cognitive or visual  impairment that are unable to visually process information because of complex visual motion we offer the ability to disable the stack effect and simply collapse the section into rows.

> To optimize for harm reduction (for user that know that have an issue with fast motion perception) we suggest to enable the collapsed mode for users with prefers-reduced-motion active.


Includes:
- Responsive mobile
- Accessibility mode
- Video support
- Layout

![Image](https://github.com/user-attachments/assets/d3962960-ec10-490b-b494-f5e1aeb9a594)

**Comment by nsolerieu** [comment]
Added further animation specs [here](https://www.figma.com/design/AEuqwByyCCch6tf7YVgk3I/Solution-Page-Templates?node-id=287-12770&t=69ysvotZ0NKbEefu-1)


![Image](https://github.com/user-attachments/assets/f3f993e2-06eb-4fe0-9160-db780d1d9f0e)

**Comment by rezrah** [comment]
This has shipped for React in `0.35.0`. Interface guidelines are up-next.
