### ISSUE TITLE
🐛 [BUG] - Image aspectRatio prop is not applied to the Image component

### ISSUE THREAD

**Issue by jjwinskill** [primer/brand#635]
## Summary

When using `Image` or `Card.Image`, setting the `aspectRatio` prop does not change the layout/size of the image.

The relevant code is here: https://github.com/primer/brand/blob/9cfc1e1ebe3f6402a5060d17d5fd13121ca798fe/packages/react/src/Image/Image.module.css#L9C1-L28C2

We are using a CSS var, `--brand-image-aspectRatio`, and then setting that var based on the class that is present in the image container. That class is correctly determined by the `aspectRatio` prop and internal helper methods, but the styles aren't being applied correctly.

It appears we are only actually using the `--brand-image-aspectRatio` css var in the `.Image--aspect-ratio-custom` class. Possibly we want to be consuming that CSS var in a class that is applied to all `Image` wrappers that have an `aspectRatio` property, and then set the CSS var within that class:

react/src/Image/Image.module.css
```css
.Image--aspect-ratio {
  aspect-ratio: var(--brand-image-aspectRatio);
}
```

react/src/Image/Image.tsx - see span className
```jsx
if (aspectRatio) {
    return (
      <span
        className={clsx(styles['Image__container'], styles['Image--aspect-ratio'], styles[`Image--aspect-ratio-${aspectRatioResolver(aspectRatio)}`])}
      >
        <img
          ...
        />
      </span>
    )
  }
```

Additionally, while we are supporting a custom `aspectRatio` value of `"custom"`, there doesn't appear to be a supported API to actually apply the `"ARwidth:ARheight"` to the image wrapper, so no custom aspect ratio is ever applied.

### Reproduction steps

1. Start storybook with `npm run start`
2. Go to the story Image / Features / Custom Image Aspect Ratio
3. From the [code in that story](https://github.com/primer/brand/blob/9cfc1e1ebe3f6402a5060d17d5fd13121ca798fe/packages/react/src/Image/Image.features.stories.tsx#L25), set the `aspectRatio` prop to each of the supported values - `"custom"`, `"1:1"`, `"16:9"`, `"16:10"`, `"4:3"` and save after each attempt
4. Observe that the correct class is applied in dev tools, but no layout changes occur

### Expected behavior

After save, the image should update to reflect the new aspect ratio

### Screenshots

- How the story appears after applying an `aspectRatio` of `"1:1"` (still 600 x 400)

![Image](https://github.com/user-attachments/assets/4a69131f-866e-4518-a2a0-1762d3957b52)

- The Image wrapper has the correct class applied but is not in the correct ratio

![Image](https://github.com/user-attachments/assets/d6e03479-09b0-4e3c-a577-f0e97c781c01)

### Browsers

Chrome

### OS

Mac

**Comment by rezrah** [comment]
This bug has been fixed in [v0.34.3 ](https://github.com/primer/brand/releases/tag/%40primer%2Freact-brand%400.34.3)
