### ISSUE TITLE
🐛 [BUG] - wrong doc link in README 

### ISSUE THREAD

**Issue by 0xMRTT** [primer/brand#68]
### Describe the bug

This is not related to an issue with brand but an issue in the README.

At the top of the README there is a link called primer.style/brand this link doesn't point to primer.style/brand but to primer.github.io/brand (this way works).

After there is a second link called primer.style/brand which point to primer style/brand (right) but primer.style/brand return a 404 error

### Reproduction steps

```bash
Go to primer.style/brand and you will get a 404 error

Go to primer.github.io/brand and it will work
```

### Expected behavior

```bash
Go to primer.style/brand and get the doc like on primer.github.io/brand
```

**Comment by rezrah** [comment]
[primer.style/brand](https://primer.style/brand/) should be up and running again. Thanks for the bug report @0xMRTT.

**Comment by 0xMRTT** [comment]
> [primer.style/brand](https://primer.style/brand/) should be up and running again. Thanks for the bug report @0xMRTT.

I'm getting an 404 error code 🙃

**Comment by rezrah** [comment]
> > [primer.style/brand](https://primer.style/brand/) should be up and running again. Thanks for the bug report @0xMRTT.
> 
> I'm getting an 404 error code 🙃

It may be the site cache. Could you try clearing it and trying again? The reverse-proxy rewrite was deployed a little while ago, so it could also need more time to propagate.

**Comment by 0xMRTT** [comment]
It's working 👍
