### ISSUE TITLE
🐛 [BUG] - Margin removed when using a `className` with `Hero.Label`

### ISSUE THREAD

**Issue by simurai** [primer/brand#757]
### Describe the bug

When adding a `className` to a `Hero.Label`, it removes the bottom margin.

### Reproduction steps

1. Go to https://primer.style/brand/components/Hero/react
2. In the editor, add `className="someClass"` to the `Hero.Label` of the first example.
3. Notice how the bottom margin is gone.

I think the `Hero-module--Hero-label--C\+rTh` class (that adds the bottom margin) gets removed from the DOM once a custom class is added?

### Expected behavior

The bottom margin should stay.

### Screenshots

![Screenshot of a label without bottom margin](https://github.com/user-attachments/assets/31d13000-1e8a-4455-ba6d-152cd9172330)

### Browsers

Chrome

### OS

Mac

**Comment by joshfarrant** [comment]
Good spot, thanks @simurai.

I've got a PR here which resolves the issue

https://github.com/primer/brand/pull/760

**Comment by rezrah** [comment]
Closing as the fix has shipped in v0.41.0
