### ISSUE TITLE
[Modification request] All links to be blue

### ISSUE THREAD

**Issue by nsolerieu** [primer/brand#770]
## Context

During the refactoring of our feature pages we've been using lots of rivers, pillars, cards, bento with links. The inconsistent color has been noticed at many occasion by different stakeholders.

- `River` links are black/white
![Image](https://github.com/user-attachments/assets/048bf241-c089-4bdb-8a0f-439ed6e0d292)

- `Cards` links are blue
![Image](https://github.com/user-attachments/assets/15187c5b-1673-43ad-8371-2cea88afefd9)

## Design suggestion

Align all components that have links to default to blue links with the following exceptions:
- Bentos that have a background image or a background gradient in use:
![Image](https://github.com/user-attachments/assets/54d2045f-33a4-424b-b687-98474b5b4576)

**Comment by simurai** [comment]
[Issue](https://github.com/github/brand-marketing-design/issues/1695) (internal link) for the feature pages.

**Comment by samoshin** [comment]
Thanks for kicking this off 🙏

**Comment by joshfarrant** [comment]
Thanks @nsolerieu — consistency makes sense to me! 

I'd be keen to get @danielguillan's thoughts on this as I don't have historical context on whether the differing colours are an oversight, or an intentional choice

**Comment by danielguillan** [comment]
The different colors were intentional but purely aesthetic choices based on the page designs these components supported when they were introduced. I also recommend updating these to use blue by default.

There is at least one additional component that doesn't use blue links, and we should consider it as well:  [SectionIntro](https://primer.style/brand/components/SectionIntro).

**Comment by samoshin** [comment]
> There is at least one additional component that doesn't use blue links, and we should consider it as well: [SectionIntro](https://primer.style/brand/components/SectionIntro).

I'm supportive of making links blue globally and by default.

**Comment by rezrah** [comment]
👋 Checking in to see how far we want to go with this change? 

We have many links on the site. Presumably we are [only targeting this specific compoinent](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-link--default) and not all links?

![Image](https://github.com/user-attachments/assets/c8c8ed25-e59a-47f6-bdb9-2676510e36b2)

For some historical context, links in Rivers were changed to black (from blue) during Site Refactor **to address hierarchical issues with adjacent CTAs**. [Link to Refactor design file.](https://www.figma.com/design/wuhr1sqnv2YEaT4F6dUBbl/Site-Refactor---Main?node-id=1115-166191&t=BWL8fEQSY5bgKBGY-4)

I believe that's also why SubNav, Breadcrumbs and other components use black links by default over blue ones. 

I think we should selectively apply this change to our most prominent high-level patterns, where link competition is less of a concern.

[There's a PR open now to update `River` and `SectionIntro` to use blue links](https://github.com/primer/brand/pull/811), as these fit that criteria and were called out in the discussion above 👍 

Wondering if we also want to update the following, as they were intentionally designed to default to black?

- [Sub nav](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-subnav--default)
- [Anchor nav](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-anchornav--default)
- [Pagination](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-pagination--default)
- [Breadcrumbs](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-breadcrumbs--default) (it [supports an optional blue variant](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-breadcrumbs-features--accent))

**Comment by rezrah** [comment]
Re-opening due to:

- Pending Figma updates (cc. @danielguillan)
- Pending answers to scope of work [here](https://github.com/primer/brand/issues/770#issuecomment-2456904792)

**Comment by rezrah** [comment]
Update: Figma changes have now shipped. No additional scope added.

**Comment by jesussandreas** [comment]
Hey @rezrah just double checking on your comment above.

All links to be blue for river components, text blocks, etc. The ones you mentioned above are okay to stay black by default.

> For some historical context, links in Rivers were changed to black (from blue)

I just want to make sure, it's the reverse. We are pivoting from black OR white to blue link colors.

**Comment by rezrah** [comment]
>> For some historical context, links in Rivers were changed to black (from blue)

> I just want to make sure, it's the reverse. We are pivoting from black OR white to blue link colors.

👍 yes that's correct. Links in River and Section Intro have been changed to blue now. [Example from our docs.](https://primer.style/brand/components/River/react).

Sorry I wasn't clear earlier. In my earlier comment I am referring to the reason why River's _previously_ had black links. It was a change made during the Site Refactor update.
