### ISSUE TITLE
[Modification request] Increase spacing between River items on Mobile

### ISSUE THREAD

**Issue by simmonsjenna** [primer/brand#783]
### Summary

We received a request (https://github.com/github/marketing-platform-services/issues/3550) to increase the spacing between River sections on mobile to create more separation between these sections and reduce confusion about which copy and images are paired within a River section.

![Image](https://github.com/user-attachments/assets/facabbbb-5fac-47b6-b132-5aa10f902d3f)

### Suggested change

Change the variable used for the padding-top and padding-bottom to: `--brand-River-spacing-outer: var(--base-size-40);` on mobile.

![Image](https://github.com/user-attachments/assets/edb2c52a-e659-46fd-be53-1c1d79a80778)

**Comment by joshfarrant** [comment]
@simmonsjenna Do you have a preference for the spacing on tablet? Currently, the `--brand-River-spacing-outer` variable has the following values:

- default (mobile) — `var(--base-size-28)`
- 768px — `var(--base-size-36)`
- 1080px — `var(--base-size-48)`

With your proposed change, this would become:

- default (mobile) — `var(--base-size-40)`
- 768px — `var(--base-size-36)`
- 1080px — `var(--base-size-48)`

In this case, the spacing drops slightly when we get to tablet viewports. I don't see that as a problem, I just wanted to check in to see if that's what you had in mind, or if you wanted to go 40/40/48, or something like that.

**Comment by danielguillan** [comment]
We recently [merged some changes](https://github.com/primer/brand/pull/767) that reversed the order of the content and visuals on small viewports and should have solved the possible confusion about which copy and images are paired. If we need further tweaks to spacing, we should use the state of the River component as of that PR in order to make the right choices.

_Please note that the changes have been merged but haven't been released yet._

**Comment by simmonsjenna** [comment]
@danielguillan Thanks for the heads-up — if all images will precede text in every River on tablet + mobile, then we don't have to be as heavy with the spacing. I still think something like this would help @joshfarrant :
default (mobile) — `var(--base-size-36)`
768px — `var(--base-size-36)`
1080px — `var(--base-size-48)`

What do you think?

**Current**
![Image](https://github.com/user-attachments/assets/d37a1458-0e83-4fae-b879-4f46bf238fcc)

**With --base-size-36**
![Image](https://github.com/user-attachments/assets/f13fd19d-1888-4065-8f29-b21504bfcd11)
