### ISSUE TITLE
[Feature request] Add image support to the Pillar component

### ISSUE THREAD

**Issue by seangolob** [primer/brand#836]
Hi PB team!

The [discussions](https://github.com/features/discussions) page has a few pillars that have images in them. 

![Image](https://github.com/user-attachments/assets/20409a9c-8c4c-4ee4-8763-bacfafedf8b8)

Currently, these are custom built and I am curious if we should standardize this feature. 

What do y'all think about adding this feature into the Pillar component? I was thinking that a `<Pillar.Image />` component could be made to support something like this.

As always, thank you for your hard work and support! ❤ 

CC @jesussandreas @simmonsjenna

**Comment by natalie-iv** [comment]
We would like to keep the rules for “pillars with images” same as for “cards with images” + a rule `Avoid using Pillars with Images for groups of 6+ items; stick to groups of 3–6. `

the following rules from cards will apply

![Image](https://github.com/user-attachments/assets/7a73852b-1f75-4aab-bbcc-5a4e79336d00)
![Image](https://github.com/user-attachments/assets/9bc6602e-cd65-42ab-88da-13e870b9b545)
![Image](https://github.com/user-attachments/assets/a2396317-bde7-4759-b959-82fae2461a43)
