### ISSUE TITLE
[a11y] Issue with `Button` and `Link` outlines on Windows 11 high contrast themes

### ISSUE THREAD

**Issue by stamat** [primer/brand#846]
### 1. Issue with the `Button` component outline in high contrast themes

For some reason there is this code, that draws the outline if `@media (forced-colors: active)`. So on focus, the outline doesn't change, it's always visible.

https://github.com/primer/brand/blob/7473042c4ea4130f2d3fe9e4de88dd28899ce727/packages/react/src/Button/Button.module.css#L211-L216

This caused the issue 👇  to be reported:

- https://github.com/github/accessibility-audits/issues/9846
- https://github.com/github/accessibility-audits/issues/9849
- https://github.com/github/accessibility-audits/issues/9850

### 2. Issue with the `Link` component outline in high contrast themes

Link has the native outline disabled and `box-shadow` used as the outline for some reason unknown to me. In `@media (forced-colors: active)` all of the `box-shadows` are removed and all of the backgrounds are set to the same color.

https://github.com/primer/brand/blob/7473042c4ea4130f2d3fe9e4de88dd28899ce727/packages/react/src/Link/Link.module.css#L40-L44

Also Link needs the `outline-offset` set to `2px`

It's just something I picked up along the way.

**All high contrast issues are Sev 4** - so it's not a hurry on this. But could be cool for this to be sorted out and be consistent. 😘

**Comment by stamat** [comment]
@rezrah @joshfarrant bros, I've made the update [here](https://github.com/primer/brand/pull/847), tested it out in the high contrast themes, it works now 💖 . Kinda need this in the new update 🙏

**Comment by rezrah** [comment]
Closing as the fix has shipped in `v0.44.0`
