### ISSUE TITLE
[Feature request] Add "muted" variant to the Hero description

### ISSUE THREAD

**Issue by seangolob** [primer/brand#849]
Hi Primer Brand team!

There are several feature pages in production that have custom styling in the `Hero.Description` component to make it appear more subtle than the default styling for the `Hero.Description`.

![Image](https://github.com/user-attachments/assets/b770cb9b-2d12-43ff-b2af-07487667b247)
![Image](https://github.com/user-attachments/assets/5907b22b-92af-4b66-b706-ebdaf71fd332)

- https://github.com/features/actions
- https://github.com/features/codespaces
- https://github.com/features/issues
- https://github.com/features/code-review
- https://github.com/features/discussions
- https://github.com/features/code-search

As an alternative, we can add this style at the implementation level. However, I wanted to see if we want to bake this into PB to get consistency for future implementations.

FWIW, the only style change that is currently being applied is changing the color of the text.

```
.heroDescriptionClass {
  color: var(--brand-color-text-muted);
}
```

Thank you PB team! Y'all are the best!

**Comment by jesussandreas** [comment]
@rezrah Questions for Site Design:

Shall we revert back to muted descriptions for all Hero descriptions?
- Could be somewhat risky, as we'd need to audit all pages for sufficient contrast

> We could go ahead with this but yes, we would then have challenges with text-muted in backgrounds, but wouldn't these be already sort of custom color coded?


Shall we allow users to choose between muted and default depending on their requirements?
Avoids regressions, but we'd need to provide guidelines on when to use muted vs default.

> Guidelines for these would be mostly contrast oriented.

- Muted on bg white or secondary.
- Primary on custom bg.

**Comment by rezrah** [comment]
Thanks @jesussandreas - sounds like you're leaning towards second option?

> users to choose between muted and default depending on their requirements?

If so, we can move this request forward by:

1. Re-enabling `variant="muted"` on `Hero.Description`, but keeping the `text-default` as the current default value.
2. Update interface guidelines to capture the use-case constraints [above](https://github.com/primer/brand/issues/849#issuecomment-2528802165).

**Comment by jesussandreas** [comment]
One more question though, by users to choose between muted and default depending on their requirements. 

How would this selection work? Depending if they have high contrast activated?
