### ISSUE TITLE
🐛 [BUG] - Arrow on CTAs not animating on hover

### ISSUE THREAD

**Issue by ywenc** [primer/brand#94]
### Describe the bug

Expected: CTA arrow should animate on hover
Current: No animation on hover

Example page: https://resources.github.com/devops/tools/compare/

the unhovered arrow starts with the classes `Primer_Brand__ExpandableArrow-module__ExpandableArrow___rkfek`, and on hover has the classes `Primer_Brand__ExpandableArrow-module__ExpandableArrow___rkfek Primer_Brand__ExpandableArrow-module__ExpandableArrow--expanded___gajDr`, but looks like there's no corresponding `ExpandableArrow--expanded` class in the css bundle.

### Reproduction steps

```bash
go to https://resources.github.com/devops/tools/compare, hover over the start a free trial CTA.
```

### Expected behavior

```bash
Expected: CTA arrow should animate on hover
```

### Screenshots

```bash
https://user-images.githubusercontent.com/20496719/195380869-d07bed09-5ba1-4429-93ee-4bcea0a959f1.mp4
```

### Browsers

Chrome

### OS

Mac

**Comment by rezrah** [comment]
@ywenc - do you happen to have css tree-shaking enabled in your production build step? 

https://user-images.githubusercontent.com/13340707/195406070-14d72ac2-954f-46ed-bfd8-fdb6405b134e.mov

I can't reproduce this in dev mode (see above).. but I'm also unable to build and inspect the prod bundles due to getting this error:

```bash
> Build error occurred
[Error: ENOENT: no such file or directory, rename '.../resources-hub/.next/export/webcasts/EMEA-Security-Learning-Journey-H2.html' -> '.../resources-hub/.next/server/pages/webcasts/EMEA-Security-Learning-Journey-H2.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '.../resources-hub/.next/export/webcasts/EMEA-Security-Learning-Journey-H2.html',
  dest: '.../resources-hub/.next/server/pages/webcasts/EMEA-Security-Learning-Journey-H2.html'
}

```

Am I missing something from Contentful?

**Comment by rfearing** [comment]
@ywenc I pretty sure this issue is occurring due to our use of Purge CSS. I wonder if we need to add exceptions or do something like pipe in PrimerBrand's compiled CSS into `/script/utils/purgecss.js`?

**Comment by rfearing** [comment]
@ywenc I'm going to close because I believe we need to fix this in Resources Hub
